### ISSUE TITLE
Suggestion: possibility to fetch all signs

### ISSUE THREAD

**Issue by siim0n** [TwinFlame-Development/horoscopeAPI#1]
Hi, would it be possible to add something to fetch all the signs at once ? I'd like to cache the informations once a day, so that I don't have to fetch each sign all day long when the information is requested

**Comment by jminutaglio** [comment]
@siim0n  yes - sure.  I can add that.

**Comment by jminutaglio** [comment]
An 'all' call has been added -> see read me.

This call will return this type of JSON format:

`[
    {
        "Aquarius": {
            "current_date": "04-05-2023",
            "compatibility": "Virgo",
            "lucky_time": "11:00",
            "lucky_number": "45",
            "mood": "Inspired",
            "description": "Wednesday, April 5th, 2023 - Your innovative and creative thinking may be in high gear today, making it an excellent time to brainstorm new ideas or solutions to problems. Trust your instincts and don't be afraid to take risks. On this day in 1614, Pocahontas married Englishman John Rolfe, reminding Aquarians of the importance of cultural exchange and diplomacy.",
            "color": "Black"
        }
    },
    {
        "Pisces": {
            "current_date": "04-05-2023",
            "compatibility": "Aries",
            "lucky_time": "02:00",
            "lucky_number": "5",
            "mood": "Happy",
            "description": "Wednesday, April 5th, 2023 - You may feel a sense of spiritual connection and desire to explore your inner world today. It's an excellent time to engage in meditation or other introspective practices. Remember to prioritize self-care and balance your emotional needs with your responsibilities. On this day in 1614, Pocahontas married Englishman John Rolfe, reminding Pisces of the importance of cultural exchange and acceptance.",
            "color": "Orange"
        }
    },
    {
        "Aries": {
            "current_date": "04-05-2023",
            "compatibility": "Aries",
            "lucky_time": "02:00",
            "lucky_number": "4",
            "mood": "Happy",
            "description": "April 5th, 2023 (Wednesday): You may feel a strong desire for freedom and independence today, Aries. It's important to balance this with responsibility and consider how your actions may impact others. On this day in 1614, Pocahontas married John Rolfe, which may be a reminder of the power of cultural exchange and diplomacy.",
            "color": "Orange"
        }
    },
    {
        "Taurus": {
            "current_date": "04-05-2023",
            "compatibility": "Virgo",
            "lucky_time": "12:00",
            "lucky_number": "46",
            "mood": "Motivated",
            "description": "April 5th, 2023 (Wednesday): Today, Taurus, you may find yourself feeling particularly creative and inspired. Use this energy to pursue your passions, whether it's through art, music, or another avenue. On this day in 1955, Winston Churchill resigned as Prime Minister of the United Kingdom, which could be relevant as Taurus tends to value tradition and stability.",
            "color": "Black"
        }
    },
    {
        "Gemini": {
            "current_date": "04-05-2023",
            "compatibility": "Pisces",
            "lucky_time": "00:30",
            "lucky_number": "99",
            "mood": "Observant",
            "description": "Wednesday, April 5th, 2023 (Gemini): Your quick wit and adaptability will come in handy today, Gemini, as you navigate unexpected changes and challenges. Remember to stay flexible and open-minded, and you'll be able to handle whatever comes your way. On this day in 1992, the first smartphone was demonstrated by IBM, highlighting the importance of technology in our lives.",
            "color": "Bronze"
        }
    },
    {
        "Cancer": {
            "current_date": "04-05-2023",
            "compatibility": "Aquarius",
            "lucky_time": "22:30",
            "lucky_number": "93",
            "mood": "Reflective",
            "description": "Wednesday, April 5th, 2023 - As a Cancer, you may be feeling particularly creative and imaginative today. You may find inspiration in art, music, or nature, and this could be a great day to express your feelings through a creative outlet. On this day in the past, in 1614, Pocahontas married English settler John Rolfe, reminding us of the power of love and connection across cultures.",
            "color": "Silver"
        }
    },
    {
        "Leo": {
            "current_date": "04-05-2023",
            "compatibility": "Aquarius",
            "lucky_time": "23:30",
            "lucky_number": "95",
            "mood": "Reflective",
            "description": "Wednesday, April 5th, 2023 - Leos are known for their creativity and love of the spotlight. Today, you may find yourself drawn to artistic or performance-related pursuits, and this could be a good day to showcase your talents. On this day in the past, in 1992, the first episode of the reality show 'The Real World' aired, a reminder that there are many paths to fame and success.",
            "color": "Silver"
        }
    },
    {
        "Virgo": {
            "current_date": "04-05-2023",
            "compatibility": "Virgo",
            "lucky_time": "11:00",
            "lucky_number": "44",
            "mood": "Inspired",
            "description": "Wednesday, April 5th, 2023 - Virgos tend to be very hardworking and diligent. Today, you may feel a strong sense of responsibility and duty, and this could be a good day to tackle important tasks or projects. On this day in the past, in 1992, the first episode of the reality show 'The Real World' aired, reminding us of the importance of authenticity and being true to ourselves.",
            "color": "Black"
        }
    },
    {
        "Libra": {
            "current_date": "04-05-2023",
            "compatibility": "Taurus",
            "lucky_time": "04:00",
            "lucky_number": "13",
            "mood": "Content",
            "description": "Wednesday, April 5th, 2023 - Libras tend to be very sociable and outgoing. Today, you may find yourself in the mood to connect with friends and loved ones, or to attend a social event. On this day in the past, in 1955, Winston Churchill resigned as Prime Minister of the United Kingdom, reminding us of the importance of leadership and diplomacy.",
            "color": "Green"
        }
    },
    {
        "Scorpio": {
            "current_date": "04-05-2023",
            "compatibility": "Leo",
            "lucky_time": "10:00",
            "lucky_number": "39",
            "mood": "Confident",
            "description": "Wednesday, April 5th, 2023: Scorpios may feel a bit of tension at work or in their daily routines. Take time to ground yourself and stay focused on your goals. On this day in 1955, Winston Churchill resigned as British Prime Minister, showing the importance of standing up for oneself and making difficult decisions.",
            "color": "Gray"
        }
    },
    {
        "Sagittarius": {
            "current_date": "04-05-2023",
            "compatibility": "Capricorn",
            "lucky_time": "19:30",
            "lucky_number": "78",
            "mood": "Composed",
            "description": "Wednesday, April 5th, 2023: As a Sagittarius, you're known for your intellectual curiosity and love of learning. Today, you may feel particularly interested in exploring new ideas and perspectives. This could be a good day to read a book, take a class, or attend a lecture. On this day in 1955, Winston Churchill resigned as Prime Minister of the United Kingdom, which reminds us of the importance of leadership and the power of words.",
            "color": "Navy blue"
        }
    },
    {
        "Capricorn": {
            "current_date": "04-05-2023",
            "compatibility": "Cancer",
            "lucky_time": "07:00",
            "lucky_number": "28",
            "mood": "Optimistic",
            "description": "Wednesday, April 5th, 2023: Your practical and analytical nature may be especially useful today, Capricorn. You may be able to approach problem-solving with a clear and level-headed mindset. On this day in 1933, President Franklin D. Roosevelt signed an executive order that ended Prohibition, which may remind you of the importance of making rational decisions that benefit society as a whole.",
            "color": "Purple"
        }
    }
]`
